#!/bin/bash -eu
echo 'rm build/*'
rm -rf ./build/
mkdir -p ./build/assets

if [ $@ = 'build' ]; then
  echo 'rm libs/*'
  rm -rf ./libs/
  mkdir -p ./libs
fi

# sugoio-core
echo $@ 'Bundling globals and editor files'
npm run $@

if [ $? -ne 0 ]; then
    echo "Bundling was get error and exit"
    exit 1
fi

echo "Copy assets and css"
cp -rf ./build/assets ./libs
cp ./build/editor.css ./libs

echo "Copy to libs"
cp ./build/editor.js ./libs/sugo-editor.min.js
cp ./build/editor-lite.js ./libs/sugo-editor-lite.min.js
cp ./build/sugo-sdk.js ./libs/sugoio-latest.min.buf.js
cp ./build/sugo-sdk.js ./libs/sugoio-latest.min.js
cp ./build/wx-mini.js ./libs/sugo-wx-mini.program.min.js
